/* Copyright (c) 2017, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_AURORA_1080P_VIDEO_H_
#define _PANEL_AURORA_1080P_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config aurora_1080p_video_panel_data = {
	"qcom,mdss_dsi_aurora_1080p_video", "dsi:0:", "qcom,mdss-dsi-panel",
	8, 0, "DISPLAY_1", 0, 0, 60, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution aurora_1080p_video_panel_res = {
	1080, 1920, 46, 30, 20, 0, 13, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info aurora_1080p_video_color = {
	24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
static char aurora_1080p_video_on_cmd0[] = {
	0x11, 0x00, 0x05, 0x80
};

static char aurora_1080p_video_on_cmd1[] = {
	0x03, 0x00, 0x29, 0xC0,
	0xF0, 0x5A, 0x5A, 0xFF,
};

static char aurora_1080p_video_on_cmd2[] = {
	0x0d, 0x00, 0x29, 0xC0,
	0xCB, 0x16, 0x00, 0x01,
	0x01, 0xDE, 0x01, 0x00,
	0x00, 0x03, 0x00, 0x06,
	0x00, 0x08, 0xFF, 0xFF,
};

static char aurora_1080p_video_on_cmd3[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xF7, 0x03, 0xFF, 0xFF,
};

static char aurora_1080p_video_on_cmd4[] = {
	0x03, 0x00, 0x29, 0xC0,
	0xF0, 0xA5, 0xA5, 0xFF,
};

static char aurora_1080p_video_on_cmd5[] = {
	0x53, 0x2c, 0x15, 0x80
};

static char aurora_1080p_video_on_cmd6[] = {
	0x51, 0x80, 0x15, 0x80
};

static char aurora_1080p_video_on_cmd7[] = {
	0x29, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd aurora_1080p_video_on_command[] = {
	{0x4, aurora_1080p_video_on_cmd0, 0x0b},
	{0x8, aurora_1080p_video_on_cmd1, 0x78},
	{0x14, aurora_1080p_video_on_cmd2, 0x78},
	{0x8, aurora_1080p_video_on_cmd3, 0x78},
	{0x8, aurora_1080p_video_on_cmd4, 0x78},
	{0x4, aurora_1080p_video_on_cmd5, 0x65},
	{0x4, aurora_1080p_video_on_cmd6, 0x78},
	{0x4, aurora_1080p_video_on_cmd7, 0x00}
};

#define AURORA_1080P_VIDEO_ON_COMMAND 8


static char aurora_1080p_videooff_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};

static char aurora_1080p_videooff_cmd1[] = {
	0x53, 0x00, 0x15, 0x80
};

static char aurora_1080p_videooff_cmd2[] = {
	0x10, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd aurora_1080p_video_off_command[] = {
	{0x4, aurora_1080p_videooff_cmd0, 0x00},
	{0x4, aurora_1080p_videooff_cmd1, 0x00},
	{0x4, aurora_1080p_videooff_cmd2, 0x78}
};

#define AURORA_1080P_VIDEO_OFF_COMMAND 3


static struct command_state aurora_1080p_video_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info aurora_1080p_video_command_panel = {
	0, 0, 0, 1, 1, 0x0, 0x0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info aurora_1080p_video_video_panel = {
	0, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration aurora_1080p_video_lane_config = {
	4, 0, 1, 1, 1, 1
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t aurora_1080p_video_timings[] = {
	0xD6, 0x34, 0x22, 0x00, 0x62, 0x66, 0x26, 0x36, 0x28, 0x03, 0x04, 0x00
};

static struct panel_timing aurora_1080p_video_timing_info = {
	0, 4, 0x7b, 0x9
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence aurora_1080p_video_reset_seq = {
	{1, 0, 1, }, {10, 10, 10, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight aurora_1080p_video_backlight = {
	1, 1, 128, 0, 2, "PMIC_8941"
};

#endif /*_PANEL_AURORA_1080P_VIDEO_H_*/
